name: no_bloc
description: Making blocs easy again. A simplified library for the original bloc approach.
version: 0.1.5
homepage: https://github.com/MohiuddinM/no_bloc

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  rxdart: ^0.24.1
  meta: ^1.1.8
  hive: ^1.0.0
  synchronized: ^2.0.0
  path: ^1.0.0
  equatable: ^1.0.0
  built_value: ^7.0.0
  test: ^1.0.0
  pedantic: ^1.0.0

dev_dependencies:
  mockito: ^4.0.0

