name: no_bloc
description: Make bloc easy again! A simple and low boilerplate implementation of the bloc state management pattern. Includes extras to work with blocs like testing, monitoring and persistence.
version: 0.4.0
homepage: https://github.com/MohiuddinM/no_bloc

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  rxdart: ^0.24.1
  meta: ^1.1.8
  hive: ^1.0.0
  synchronized: ^2.0.0
  path: ^1.0.0
  equatable: ^1.0.0
  built_value: ^7.0.0
  test: ^1.0.0
  pedantic: ^1.0.0

dev_dependencies:
  mockito: ^4.0.0

